### ISSUE TITLE
tkinter error

### ISSUE THREAD

**Issue by MongooseSec** [0xPoly/Centry#11]
I'm getting this when trying to run Centry as root:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.2/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python3.2/multiprocessing/process.py", line 116, in run
    self._target(_self._args, *_self._kwargs)
  File "./centry.py", line 240, in start
    title["font"] = ('',32,'bold')
  File "/usr/lib/python3.2/tkinter/__init__.py", line 1227, in **setitem**
    self.configure({key: value})
  File "/usr/lib/python3.2/tkinter/**init**.py", line 1220, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.2/tkinter/__init__.py", line 1211, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: expected integer but got "bold"

**Comment by v998** [comment]
which version of python are you using?
I got something similar when I use an incorrect version of Python

**Comment by MongooseSec** [comment]
Yes, I was using python3

**Comment by v998** [comment]
Check if tkinter is missing in Python
Try installing tkinter by something like
`apt-get install python3-tkinter`
